# Generated by Django 5.0.6 on 2024-06-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=20)),
                ('customer_code', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('stage_name', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('due_date', models.DateField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditsNotesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('customer_code', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bss_app.bookingpaymentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='CreditsNotesReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('credits_notes_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bss_app.creditsnotesmaster')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceiptMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('customer_code', models.CharField(max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bss_app.bookingpaymentschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceiptReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('receipt_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bss_app.paymentreceiptmaster')),
            ],
        ),
    ]
